# Generated by Django 4.2.3 on 2023-07-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=126)),
                ("rollnumber", models.CharField(max_length=126)),
                ("mail_id", models.EmailField(max_length=256)),
                ("password", models.CharField(max_length=126)),
                ("dob", models.DateField()),
            ],
        ),
    ]
